### ISSUE TITLE
Z10 can't type main "$"

### ISSUE THREAD

**Issue by halfnibble** [mordak/Term48#1]
You can't use the "$" on the main `?123` keys, but pressing `?123`, then `&%`, you can use the "$" in the middle.

@lewellyn reported.

**Comment by mordak** [comment]
Yup. This is an OS bug introduced in 10.3.1. Same issue affects the passport and any other Core Native app. Reported and confirmed with BlackBerry (BBTEN-2974). They say it will be fixed in a release after 10.3.1, so I am guessing shortly in 10.3.2.

**Comment by dkonigsberg** [comment]
I'm using a Passport with 10.3.2.680, and I can confirm that I'm not experiencing this bug.

**Comment by mordak** [comment]
Oh that's great news! Thanks dkonigsberg!

**Comment by mordak** [comment]
Confirmed fixed in 10.3.2.
