### ISSUE TITLE
Main window not accepting keyboard input

### ISSUE THREAD

**Issue by ardangelo** [mordak/Term48#19]
Unable to type on main window after startup. Cursor appears but no keyboard input is possible.
Activating the "Meta" mode with touch target does work, so would mean that SDL input is at least partially functioning.

**Comment by ardangelo** [comment]
Ran some debugging with GDB, in the main event loop in `main.c` line 1552, every key-based SDL event type is coming out as "unknown" type 13.
Many other types of interactions also appear to generate SDL event type 13 and it doesn't look like `event.key` holds anything meaningful for a key-based event.

Compiles using the release versions of SDL/TouchControlOverlay, but crashes before `main` (dynamic loading issues?) Suspect that despite a successful compilation there may be some mismatch between release libraries and dev branch code.

**Comment by mordak** [comment]
Pushed some changes that do the trick for me. Had to mess with some flags and update the SDL to follow the term48 branch, which has a bunch of custom stuff to get events into the terminal. If it works for you, then you're all set.

**Comment by ardangelo** [comment]
Thanks, works great. Nice to finally get a working build going!
