### ISSUE TITLE
ctrl key

### ISSUE THREAD

**Issue by schef** [mordak/Term48#2]
Hey. Where or how can I press ctrl. I use q10.

**Comment by mordak** [comment]
Hello,

You can press Ctrl by entering metamode, then pressing c. 

To enter metamode, tap the top left corner of the screen, or hold the spacebar for a second. You will see a green M in the top right corner showing you are in metamode. ‎From metamode, press the c key to hold down Ctrl. You will see a green C in the top right corner of the screen indicating that Ctrl is pressed. The next key you press will be sent with the Ctrl key down. 

For example, to press Ctrl-c:
Tap the top left corner of the screen to enter metamode;
Press c;
Press c. 

I hope this helps. How to send the various modifier keys and the details on how metamode works is in the README, along with the various configuration options. You can read the README by opening Term48 and typing 'less README' (without the quotes).                                                                                                                                      

Cheers,                                                                                                                                                                                                   Todd

**Comment by schef** [comment]
Thanks. I was trying to find how to use it but didnt.
