### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by ardangelo** [mordak/Term48#24]
![term48](https://user-images.githubusercontent.com/4421576/30722207-7e271766-9ef5-11e7-92dc-fdb1d68dec49.png)

Something that emphasizes the keyboard. Thoughts?

**Comment by mordak** [comment]
Hmm. I'd prefer that the dominant text on the icon was not 'cd ~'. What if the vertical split was the other way, with the keys taking 2/3 of the room, and the prompt taking 1/3, and the prompt was just the prompt? The extra row of keys could hold the 48?

**Comment by ardangelo** [comment]
![term48-tworow](https://user-images.githubusercontent.com/4421576/31201892-015f6c0c-a926-11e7-9133-db5a29aa6793.png)


Like this?

**Comment by mordak** [comment]
Hmm.. Still not sold. If I had to choose between the current icon and this one, I would pick the current one. Out of curiosity, what is it about the current icon that motivated you to suggest changing it?

**Comment by ardangelo** [comment]
Was just a bit bored and thought of the design, no big deal either way.
