### ISSUE TITLE
How to use ssh

### ISSUE THREAD

**Issue by robin8588** [mordak/Term48#26]
Hi ,thanks for the great tool ,I want to use ssh ,I found scp ,but did not found ssh ,thanks

**Comment by khapota** [comment]
Hi, could you provide error message when run ssh? Term48 has ssh command by default.

**Comment by mordak** [comment]
The ssh binary is located inside the Term48 bundle at app/native/root/bin/ssh. The path to this is set in the main executable, so you should be able to run ssh by just typing 'ssh'. If you have reset your $PATH in your shell in .profile or some other configuration file, then you might not be able to find it anymore. In this case, just add the correct path to your $PATH, or don't clobber the default $PATH by using PATH=/my/custom/stuff/:$PATH or equivalent.

The scp you found is probably the one that ships with bb10 out of the box. Term48 also ships a scp that will work, in the same directory as ssh.

**Comment by robin8588** [comment]
HI thanks for replay ,I still not find ssh ,can you give me the Absolute Path of ssh
![img_00000006](https://user-images.githubusercontent.com/4414905/33987436-d26ddd44-e0fb-11e7-842e-a0be7eef9bf8.png)

**Comment by mordak** [comment]
The ssh binary is at `/accounts/1000/appdata/ca.mordak.Term48.gYABgJC2m1SvBDfQMWQBsIohLnw/app/native/root/bin/ssh`

Your path there is wrong - it should contain `$HOME/../app/native/root/bin`. The warning at the top there about no controlling tty is also unusual. Can you tell me what device you have, and what builds of BB10 and Term48 you have installed? If you have a Playbook, then Term48 on that device does not ship with ssh. Old versions of the playbook-dev-tools repo did build on the playbook, so you can build it yourself if you are feeling adventurous, but the playbook has not been really supported for years.

**Comment by robin8588** [comment]
my Q10 is good ,playbook not working ,Thanks.good job
