### ISSUE TITLE
ssh/scp binaries

### ISSUE THREAD

**Issue by singpolyma** [mordak/Term48#6]
I know I could compile them myself, but was hoping not to. Using the ones from bgshellplus, but it seems they sometimes get confused and use the wrong tty? bgshell always seems to be on ttyp1 and term48 always on ttyp0. Maybe there's something hardcoded, but it does work sometimes and sometimes when it doesn't I open bgshell and the password prompt shows up over there for an ssh I ran in term48 :P I'm asking the bgshell author about it, but really having a few more of these core utilities included with this app might be helpful.

**Comment by mordak** [comment]
Ack, thank you for the vote. Including ssh binaries is a very common feature request. I've been hoping to do it 'right' by getting a package manager up and running, but that isn't looking likely anytime soon, so just bundling ssh will go on the list. 

Incidentally, if you drop me a line via email (mordak48@gmail.com) I can send you the compiled ssh binaries from the dev-tools.

**Comment by singpolyma** [comment]
hmm, yes. I was thinking about package management longer-term. I have a portable implementation of much of apt hanging around from an old project.. hmm. Anyway, I'll email you :)

**Comment by mordak** [comment]
ssh, scp, and sftp shipped in 0.4.1.4 today. Thanks for your help testing! If you want to see the source for the wrappers around scp/sftp, it is here:

https://github.com/mordak/playbook-dev-tools/tree/master/bootstrap/openssh/wrappers
